import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import NonSSRWrapper from "@/components/NonSSRWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "h-full font-sans antialiased relative w-full bg-color",
          inter.className
        )}
      >
        <NonSSRWrapper>
          <main className="relative min-h-screen flex flex-col text-white">
            {children}
          </main>
        </NonSSRWrapper>
      </body>
    </html>
  );
}
