import { Toaster } from "@/components/ui/sonner";
import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import SessionProvider from "@/components/SessionProvider";
import { getServerSession } from "next-auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();

  return (
    <html lang="en">
      <body
        className={cn(
          "h-full font-sans antialiased relative w-full bg-color",
          inter.className
        )}
      >
        <main className="relative min-h-screen flex flex-col text-white">
          <SessionProvider session={session}>
            {children}
            <Toaster />
          </SessionProvider>
        </main>
      </body>
    </html>
  );
}
